Rewrite debug docs
UniPiTechnology/evok pull request #142
Opened 2024-04-08 07:56 UTC by cewbdex

Please review and merge eventually.

2024-04-08 10:34 UTC, kratochvil01 requested changes

2024-04-08 10:34 UTC, kratochvil01 commented on docs/debugging.md
> +journalctl -e -u evok -u unipi-one-modbus
Remove unipi-one-modbus. This service running only on unipi 1.1

2024-04-08 15:06 UTC, cewbdex commented on docs/debugging.md
> +journalctl -e -u evok -u unipi-one-modbus
Yes, I know, but it does not throw any error, when the service is not present, so I think of this as a feature, not a bug. Provides more debug info this way, what do you think of my solution with this in mind?

2024-04-08 16:18 UTC, kratochvil01 commented on docs/debugging.md
> +journalctl -e -u evok -u unipi-one-modbus
unipi-one-modbus has nothing to do with Evok. It is a HW to Modbus TCP converter just like the unipitcp service for other unipi controllers. This service is not related to the tuning of the Evok as such.

2024-04-09 06:19 UTC, cewbdex commented on docs/debugging.md
> +journalctl -e -u evok -u unipi-one-modbus
Thus, it might provide relevant information that would help the debugging. But I see your point.

2024-04-10 11:00 UTC, kratochvil01 approved these changes

2024-04-10 11:58 UTC, merged