Doc: Rework installation section
UniPiTechnology/evok pull request #151
Opened 2024-04-29 08:24 UTC by kratochvil01

2024-04-29 10:25 UTC, cewbdex requested changes
L44 and L69 need to reflect changes.

2024-04-29 10:26 UTC, cewbdex requested changes

2024-04-29 10:26 UTC, cewbdex commented on docs/installation.md
> +To install Evok, you will have to [prepared OS](#OS-preparation) and then [install the package](#installing-and-updating-evok).
*prepare the OS*

2024-04-29 12:41 UTC, kratochvil01 commented on docs/installation.md
> +To install Evok, you will have to [prepared OS](#OS-preparation) and then [install the package](#installing-and-updating-evok).
Done

2024-04-30 07:11 UTC, cewbdex requested changes

2024-04-30 07:11 UTC, cewbdex commented on docs/installation.md
> +**To be able use the beta version, you need to have [prepared OS](#OS-preparation) already installed**. You can switch to the beta version of Evok by adding the repository to the apt sources:
I would use:
You need to have the OS prepared already.

2024-04-30 12:00 UTC, martytriska approved these changes

2024-05-02 05:51 UTC, cewbdex requested changes
Looks ok, minor tweaks below.

2024-05-02 05:51 UTC, cewbdex commented on docs/installation.md
> +Make sure you have [prepared the OS](#OS-preparation) correctly first. This works both for installing and updating.
```suggestion
Make sure you have [prepared the OS](#OS-preparation) correctly first. Following steps work both for installing and updating.
```

This will make it more clear.

2024-05-02 05:51 UTC, cewbdex commented on docs/installation.md
Update the link below on L12, so it points to the section below. But it's under beta repos, which I don't know if will be changed.

2024-05-02 07:40 UTC, kratochvil01 commented on docs/installation.md
Link in L12 is OK. The link refers to unipi kb with latest no-beta images. Or what did you mean?

2024-05-06 13:46 UTC, merged