Doc: Add changes to README.
UniPiTechnology/evok pull request #152
Opened 2024-04-29 08:54 UTC by kratochvil01

2024-04-29 10:20 UTC, cewbdex requested changes

2024-04-29 10:20 UTC, cewbdex commented on README.md
> +- RO and DO was split separate endpoints in the API (/rest/relay & /rest/output).
RO and DO were split into sep*

2024-04-30 07:50 UTC, cewbdex requested changes

2024-04-30 07:50 UTC, cewbdex commented on README.md
> +- RO and DO were split separate endpoints in the API (/rest/relay & /rest/output).
```suggestion
- RO and DO were split into separate endpoints in the API (/rest/relay & /rest/output).
```

2024-04-30 07:53 UTC, cewbdex approved these changes

2024-04-30 12:40 UTC, martytriska approved these changes

2024-05-02 06:08 UTC, cewbdex commented on README.md
> +- Relay entities are excluded from the 'output' endpoint and have a separate 'relay' endpoint.
```suggestion
- Relay entities are excluded from the `output` endpoint and have a separate `relay` endpoint.
```

2024-05-02 07:52 UTC, merged