Add circuit documentation
UniPiTechnology/evok pull request #160
Opened 2024-05-15 11:43 UTC by kratochvil01

I have added a section on device circuit.

I'm not sure where this section belongs. It is currently located in the API overview, but I think it is hard to find it here. I think it belongs thematically to the API, but maybe it belongs more in `index.md`, or maybe it deserves a separate file `circuit.md`. 

Maybe it doesn't make sense to create a circuit for `data_point`. In Evok 2 this entity was known as `unit_register` and it made sense to create a circuit based on the Modbus register address. But now this entity has a more general meaning and so it might make sense to change the creation of its circuit based on the variable name.

2024-05-15 21:16 UTC, tomashora commented
- [ ] Navrh uvodniho textu: Circuit is a unique identifier of a particular entity (input, output, or function) of each device. The circuit is created automatically during initialization of Evok according to the table below.
- [ ] Do tabulky doplnit sloupecek s priklady, jak to muze vypadat
- [ ] V tabulce a v popisu pod tabulkou nahradit <count> za <number>... ale koukam, ze count je vsude v konfiguraci. Blby je ze count znamena počet, coz v anlictine nedava smysl a ma byt spravne number
- [ ] 1-wire example - ktery z formatu ma byt pouzit? s teckami nebo bez?

2024-05-16 10:04 UTC, cewbdex requested changes

2024-05-16 10:04 UTC, cewbdex commented on docs/apis.md
> +- <number\>: Sequence number (is based on the 'count' parameter in the [HW definition]).
What does it do? It's hard to understand.

2024-05-16 11:31 UTC, kratochvil01 commented on docs/apis.md
> +- <number\>: Sequence number (is based on the 'count' parameter in the [HW definition]).
What you mean? It is legend for variables used in the table

2024-05-16 11:32 UTC, kratochvil01 commented on docs/apis.md
> +
It says this in the PR description. The placement of this section is up for discussion.

2024-05-16 11:33 UTC, kratochvil01 commented on docs/apis.md
> +# Device circuit
This depends on the placement of this section. This has not been decided yet.

2024-05-16 11:36 UTC, kratochvil01 commented on docs/apis.md
> +
I don't think the configuration is the right place to put this. It's about accessing individual entities using the API. The way the circuits are created is not configurable.

2024-05-22 11:35 UTC, merged