Add First steps to index.md
UniPiTechnology/evok pull request #179
Opened 2024-08-07 10:48 UTC by cewbdex

2024-08-12 07:05 UTC, kratochvil01 requested changes

2024-08-12 07:05 UTC, kratochvil01 commented on docs/index.md
> +    - Switch off the RO 2_01 relay: `curl --request POST --url http://192.168.1.2:8080/json/ro/2_01 --header 'Accept: application/json' --header 'Content-Type: application/json' --data '{"value": 0}'
2th section is not on all Unipi controllers. For demonstration it is better to use DO1_1. Its on most controllers.

2024-08-12 07:05 UTC, kratochvil01 commented on docs/index.md
> +- You can try to use the API in bash ([more information about API](./apis.md)):
In default configuration is API only for local host. You must change configuration or use nginx to API access (configured by evok-web)

2024-08-12 07:05 UTC, kratochvil01 commented on docs/index.md
> +- If you installed the web, you can try opening `http://<unit-IP-adrress>/` in your web browser and you can turn on and off relays or digital outputs.
If node-red is installed, it is possible to test Evok using the node-red dashboard. At the same time it is not necessary to install Evok. Maybe it would be better to split these 2 approaches into separate sections?

2024-08-12 08:42 UTC, cleveHEX commented on docs/index.md
> +- If you installed the web, you can try opening `http://<unit-IP-adrress>/` in your web browser and you can turn on and off relays or digital outputs.
Added separate sections.

2024-08-12 08:42 UTC, cleveHEX commented on docs/index.md
> +- You can try to use the API in bash ([more information about API](./apis.md)):
Can you check it?

2024-08-12 08:42 UTC, cleveHEX commented on docs/index.md
> +    - Switch off the RO 2_01 relay: `curl --request POST --url http://192.168.1.2:8080/json/ro/2_01 --header 'Accept: application/json' --header 'Content-Type: application/json' --data '{"value": 0}'
Addressed.

2024-08-12 08:58 UTC, kratochvil01 requested changes

2024-08-12 08:58 UTC, kratochvil01 commented on docs/index.md
> +    Open `http://<unit-IP-adrress>/` and toggle some outputs.
It would be good to put a screenshot here for a better idea.

2024-08-12 08:58 UTC, kratochvil01 commented on docs/index.md
> +    Open `http://<unit-IP-adrress>:1880/` and try the default Node-RED project.
It would be good to put a screenshot here for a better idea.

2024-08-12 08:58 UTC, kratochvil01 commented on docs/index.md
> +=== "Bash"
Maybe link to `./apis/json#Examples` ??

2024-08-12 08:58 UTC, kratochvil01 commented on docs/index.md
> +    - Switch off the DO 1_01 relay: `curl --request POST --url http://192.168.1.2:8080/json/do/1_01 --header 'Accept: application/json' --header 'Content-Type: application/json' --data '{"value": 0}'
Switch ... the DO 1_01 ~~relay~~

2024-08-15 08:28 UTC, cleveHEX commented on docs/index.md
> +=== "Bash"
Where exactly, can you suggest exact change?
![obrazek](https://github.com/user-attachments/assets/8611f9da-e7da-46bd-9112-d35d091aaf4f)

2024-08-15 10:58 UTC, cleveHEX commented
Changes implemented.

2024-08-19 07:41 UTC, kratochvil01 requested changes

2024-08-19 07:41 UTC, kratochvil01 commented on docs/index.md
> +- You can try to use the API using bash or Node-RED, ([more information about API](./apis.md)):
```suggestion
- You can try to use the API using bash or Node-RED, ([more information about API](./apis/json#Examples)):
```

2024-08-19 07:41 UTC, kratochvil01 commented on docs/index.md
> +=== "Bash"
Suggestion added

2024-08-19 07:52 UTC, kratochvil01 commented on docs/index.md
> +=== "Node-RED"
Add information (and photo?) about default node-red dashboard (for many people the important information is that the dashboard is on the endpoint '/ui')

2024-08-19 07:53 UTC, kratochvil01 requested changes

2024-08-19 07:53 UTC, kratochvil01 commented on docs/index.md
> +=== "Node-RED"
Add information (and photo?) about default node-red dashboard (for many people the important information is that the dashboard is on the endpoint '/ui')

2024-08-20 07:02 UTC, kratochvil01 approved these changes

2024-08-20 08:16 UTC, merged